/**
 * `pi-hashline-edit-pro` anchor resolution (#2423 review round 1, finding F1).
 *
 * ## Why this module exists
 *
 * `pi-hashline-edit-pro` addresses lines by a bare THREE-CHARACTER base62
 * anchor — `"aB3"`, never `"42"`. Its schema says so in as many words
 * (`src/payload-contract.ts`: *"Bare 3-char anchor only (e.g. \"aB3\")"*), and
 * its parser accepts exactly `trimmed.length === ANCHOR_LEN && ALPH_RE.test()`
 * (`src/hashline/parse.ts`). The first cut of the shape adapter in
 * `clients/mutating-tool.ts` read those fields as DECIMAL line numbers, so
 * against the real extension every anchor was "malformed" and the adapter
 * blocked a working edit tool.
 *
 * This module reproduces the extension's own line-hash function so pi-lens can
 * map an anchor back to a line, and does it from the extension's source rather
 * than from a guess. Everything below is a port of
 * `pi-hashline-edit-pro@8f027ca1c2a0796ccf1c15bd5a0d12db5d9fb9f0`
 * (github.com/YuGiMob/pi-hashline-edit-pro, branch `master`):
 *
 * - `src/hashline/alphabet.ts` — `HASH_LEN = 3`, the 62-character alphabet
 *   `A-Za-z0-9`.
 * - `src/hashline/hash.ts` — `hashSource` (strip `\r`, `trimEnd`, truncate to
 *   `MAX_HASH_SOURCE_BYTES = 500` UTF-8 bytes on a code-point boundary),
 *   `baseIdx = (xxh32(source) >>> 14) % 62**3`, and open-addressed collision
 *   probing with stride `62**2 + 62 + 1` over a used-index bitset.
 * - `src/hashline/hasher.ts` — `xxh32` is `xxhash-wasm`'s `h32`, i.e. standard
 *   XXH32 with seed 0 over the UTF-8 bytes. Reimplemented here in ~40 lines of
 *   integer arithmetic rather than taking a runtime dependency (pi installs
 *   pi-lens with `npm install --omit=dev`, so a hashing dep would ship to every
 *   user for one adapter).
 * - `src/hashline/resolve.ts` — `resAnchorFromMap`: an anchor resolves ONLY
 *   when it matches exactly one line. Zero matches is `not_found`, two or more
 *   is `ambiguous`, and the extension refuses both rather than guessing.
 *
 * `tests/clients/hashline-anchor.test.ts` pins the port against a vector table
 * generated by RUNNING the upstream code with the real `xxhash-wasm`, so a
 * drift in either direction is a red test rather than a silent misattribution.
 *
 * ## The one honest approximation
 *
 * The live extension does not always recompute hashes: it persists a per-file
 * snapshot (`src/hash-store.ts`) and, across an edit, carries a surviving
 * line's old hash forward (`mapStableHashes`) so anchors stay stable while the
 * agent works. pi-lens has no access to that store, so it recomputes with
 * `_lineHashesPure`. For a line whose content is unique in the file the two
 * agree; where probing order differs they can disagree, and the anchor then
 * resolves to nothing here.
 *
 * That is why an unresolved anchor is NEVER a blocking verdict. pi-lens's
 * uncertainty about a third-party tool's addressing is not evidence that the
 * agent's edit is wrong. An unresolved anchor degrades to "mutation recognized,
 * lines unknown" — the same state a host `edit` with an unknown schema reaches
 * on master — so the file still gets its turn-state entry, its deferred format
 * and its change-log receipt.
 */
import * as nodeFs from "node:fs";

/** `HASH_LEN` in `src/hashline/alphabet.ts`. */
export const HASHLINE_ANCHOR_LENGTH = 3;

/** `ALPH` in `src/hashline/alphabet.ts`. Order is load-bearing: it is the digit set. */
const ALPHABET =
	"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

/** `HASH_SPACE` — 62**3 = 238328 addressable anchors. */
const HASH_SPACE = ALPHABET.length ** HASHLINE_ANCHOR_LENGTH;

/** `HASH_PROBE_STRIDE` — 62**2 + 62 + 1, the open-addressing step. */
const HASH_PROBE_STRIDE = ALPHABET.length ** 2 + ALPHABET.length + 1;

/** `MAX_HASH_SOURCE_BYTES` in `src/constants.ts`. */
const MAX_HASH_SOURCE_BYTES = 500;

const BITSET_WORDS = Math.ceil(HASH_SPACE / 32);

const ANCHOR_TOKEN_RE = /^[A-Za-z0-9]{3}$/;

// --- XXH32 (seed 0), the algorithm behind `xxhash-wasm`'s `h32` -------------

const XXH_PRIME1 = 0x9e3779b1;
const XXH_PRIME2 = 0x85ebca77;
const XXH_PRIME3 = 0xc2b2ae3d;
const XXH_PRIME4 = 0x27d4eb2f;
const XXH_PRIME5 = 0x165667b1;

function rotl32(value: number, bits: number): number {
	return (value << bits) | (value >>> (32 - bits));
}

function xxhRound(acc: number, input: number): number {
	return (
		Math.imul(
			rotl32((acc + Math.imul(input, XXH_PRIME2)) | 0, 13),
			XXH_PRIME1,
		) | 0
	);
}

/**
 * Standard XXH32 with seed 0 over `bytes`. Returns an unsigned 32-bit integer,
 * matching `xxh32()` in `src/hashline/hasher.ts`.
 */
export function xxh32Bytes(bytes: Uint8Array): number {
	const length = bytes.length;
	let index = 0;
	let hash: number;
	if (length >= 16) {
		const limit = length - 16;
		let v1 = (XXH_PRIME1 + XXH_PRIME2) | 0;
		let v2 = XXH_PRIME2 | 0;
		let v3 = 0;
		let v4 = -XXH_PRIME1 | 0;
		do {
			v1 = xxhRound(v1, readU32(bytes, index));
			v2 = xxhRound(v2, readU32(bytes, index + 4));
			v3 = xxhRound(v3, readU32(bytes, index + 8));
			v4 = xxhRound(v4, readU32(bytes, index + 12));
			index += 16;
		} while (index <= limit);
		hash =
			(rotl32(v1, 1) + rotl32(v2, 7) + rotl32(v3, 12) + rotl32(v4, 18)) | 0;
	} else {
		hash = XXH_PRIME5 | 0;
	}
	hash = (hash + length) | 0;
	while (index + 4 <= length) {
		hash =
			Math.imul(
				rotl32((hash + Math.imul(readU32(bytes, index), XXH_PRIME3)) | 0, 17),
				XXH_PRIME4,
			) | 0;
		index += 4;
	}
	while (index < length) {
		hash =
			Math.imul(
				rotl32((hash + Math.imul(bytes[index]!, XXH_PRIME5)) | 0, 11),
				XXH_PRIME1,
			) | 0;
		index += 1;
	}
	hash = (hash ^ (hash >>> 15)) | 0;
	hash = Math.imul(hash, XXH_PRIME2) | 0;
	hash = (hash ^ (hash >>> 13)) | 0;
	hash = Math.imul(hash, XXH_PRIME3) | 0;
	hash = (hash ^ (hash >>> 16)) | 0;
	return hash >>> 0;
}

function readU32(bytes: Uint8Array, offset: number): number {
	return (
		bytes[offset]! |
		(bytes[offset + 1]! << 8) |
		(bytes[offset + 2]! << 16) |
		(bytes[offset + 3]! << 24) |
		0
	);
}

// --- The line-hash function -------------------------------------------------

/** `canon` in `src/hashline/hash.ts`. */
function canon(line: string): string {
	return line.replace(/\r/g, "").trimEnd();
}

/** `splitLines` in `src/utils.ts`. An empty file is ONE empty line. */
function splitLines(text: string): string[] {
	if (text.length === 0) return [""];
	const lines = text.split("\n");
	return text.endsWith("\n") ? lines.slice(0, -1) : lines;
}

/**
 * `hashSource` in `src/hashline/hash.ts`, as bytes.
 *
 * Upstream truncates the STRING to 500 UTF-8 bytes by iterating code points
 * (`truncateToBytes` in `src/utils.ts`) and then hashes its UTF-8 encoding.
 * Cutting the encoded buffer back to the last non-continuation byte is the
 * same operation, because a UTF-8 code point occupies contiguous bytes.
 */
function hashSourceBytes(line: string): Uint8Array {
	const bytes = Buffer.from(canon(line), "utf8");
	if (bytes.length <= MAX_HASH_SOURCE_BYTES) return bytes;
	let cut = MAX_HASH_SOURCE_BYTES;
	while (cut > 0 && (bytes[cut]! & 0xc0) === 0x80) cut -= 1;
	return bytes.subarray(0, cut);
}

function indexToAnchor(index: number): string {
	let out = "";
	let remaining = index;
	for (let digit = 0; digit < HASHLINE_ANCHOR_LENGTH; digit += 1) {
		out = ALPHABET[remaining % ALPHABET.length]! + out;
		remaining = Math.floor(remaining / ALPHABET.length);
	}
	return out;
}

function getBit(bits: Uint32Array, index: number): boolean {
	return ((bits[index >>> 5]! >>> (index & 31)) & 1) !== 0;
}

function setBit(bits: Uint32Array, index: number): void {
	bits[index >>> 5]! |= 1 << (index & 31);
}

function nextZeroBit(bits: Uint32Array, start: number): number {
	let index = start % HASH_SPACE;
	for (let step = 0; step < HASH_SPACE; step += 1) {
		if (!getBit(bits, index)) return index;
		index += HASH_PROBE_STRIDE;
		if (index >= HASH_SPACE) index -= HASH_SPACE;
	}
	// Upstream throws `[E_FILE_TOO_LARGE]` here. pi-lens is an observer, so it
	// reports "cannot address this file" instead of failing the caller.
	return -1;
}

/**
 * `_lineHashesPure` in `src/hashline/hash.ts`: one anchor per line of
 * ALREADY-NORMALIZED content (BOM stripped, CRLF folded to LF).
 *
 * Returns `undefined` for a file with more lines than the anchor space can
 * address, which is where upstream raises `[E_FILE_TOO_LARGE]`.
 */
export function computeHashlineAnchors(content: string): string[] | undefined {
	const lines = splitLines(content);
	if (lines.length > HASH_SPACE) return undefined;
	const anchors = new Array<string>(lines.length);
	const used = new Uint32Array(BITSET_WORDS);
	let hint = 0;
	const sourceCache = new Map<string, number>();
	for (let i = 0; i < lines.length; i += 1) {
		const line = lines[i]!;
		let baseIndex = sourceCache.get(line);
		if (baseIndex === undefined) {
			baseIndex = (xxh32Bytes(hashSourceBytes(line)) >>> 14) % HASH_SPACE;
			sourceCache.set(line, baseIndex);
		}
		if (!getBit(used, baseIndex)) {
			setBit(used, baseIndex);
			hint = baseIndex + HASH_PROBE_STRIDE;
			anchors[i] = indexToAnchor(baseIndex);
			continue;
		}
		const probed = nextZeroBit(used, hint);
		if (probed < 0) return undefined;
		setBit(used, probed);
		hint = probed + HASH_PROBE_STRIDE;
		anchors[i] = indexToAnchor(probed);
	}
	return anchors;
}

// --- Anchor tokens ----------------------------------------------------------

/**
 * The anchor token an edit-pro request carries, or `undefined` when the value
 * is not one. Mirrors `parseRef` in `src/hashline/parse.ts`: trim, then require
 * exactly three characters from the alphabet. A decimal line number is NOT an
 * anchor.
 */
export function normalizeHashlineAnchorToken(
	value: unknown,
): string | undefined {
	if (typeof value !== "string") return undefined;
	const trimmed = value.trim();
	return ANCHOR_TOKEN_RE.test(trimmed) ? trimmed : undefined;
}

// --- Resolution against the file on disk ------------------------------------

/** Why an anchor did not become a line. Reported, never blocked on. */
export type HashlineAnchorFailure =
	| "not_an_anchor"
	| "file_unreadable"
	| "file_too_large"
	| "anchor_not_found"
	| "anchor_ambiguous";

export interface HashlineAnchorResolution {
	/** 1-based line, present only when exactly one line carries the anchor. */
	line?: number;
	failure?: HashlineAnchorFailure;
}

/**
 * Files larger than this are not anchor-resolved. The extension itself caps at
 * `MAX_HASH_LINES` (62**3 lines); this byte cap keeps the synchronous read on
 * the tool_call path bounded regardless of line length.
 */
const MAX_ANCHOR_FILE_BYTES = 4 * 1024 * 1024;

interface AnchorIndexEntry {
	mtimeMs: number;
	size: number;
	/** anchor -> 1-based line, or `null` when more than one line carries it. */
	index: Map<string, number | null>;
}

/**
 * Bounded memo. `classifyMutatingTool` runs several times per tool call and the
 * same file is asked about repeatedly; without this every ask re-reads and
 * re-hashes the file. Keyed by path and invalidated by mtime/size, so an edit
 * between two asks is never answered from the stale index.
 */
const ANCHOR_INDEX_CACHE = new Map<string, AnchorIndexEntry>();
const ANCHOR_INDEX_CACHE_LIMIT = 8;

/** Test seam: drop the memo so a fixture rewrite is never answered from cache. */
export function _resetHashlineAnchorCacheForTests(): void {
	ANCHOR_INDEX_CACHE.clear();
}

function buildAnchorIndex(
	filePath: string,
): { index: Map<string, number | null> } | { failure: HashlineAnchorFailure } {
	let stats: nodeFs.Stats;
	try {
		stats = nodeFs.statSync(filePath);
	} catch {
		return { failure: "file_unreadable" };
	}
	if (!stats.isFile()) return { failure: "file_unreadable" };
	if (stats.size > MAX_ANCHOR_FILE_BYTES) return { failure: "file_too_large" };

	const cached = ANCHOR_INDEX_CACHE.get(filePath);
	if (
		cached &&
		cached.mtimeMs === stats.mtimeMs &&
		cached.size === stats.size
	) {
		return { index: cached.index };
	}

	let raw: string;
	try {
		raw = nodeFs.readFileSync(filePath, "utf8");
	} catch {
		return { failure: "file_unreadable" };
	}
	// `readNormFile` in the extension strips the BOM and folds line endings to
	// LF before hashing, so the same normalization has to happen here.
	const normalized = (raw.startsWith("﻿") ? raw.slice(1) : raw)
		.replace(/\r\n/g, "\n")
		.replace(/\r/g, "\n");
	const anchors = computeHashlineAnchors(normalized);
	if (anchors === undefined) return { failure: "file_too_large" };

	const index = new Map<string, number | null>();
	for (let i = 0; i < anchors.length; i += 1) {
		const anchor = anchors[i]!;
		index.set(anchor, index.has(anchor) ? null : i + 1);
	}
	if (ANCHOR_INDEX_CACHE.size >= ANCHOR_INDEX_CACHE_LIMIT) {
		const oldest = ANCHOR_INDEX_CACHE.keys().next().value;
		if (oldest !== undefined) ANCHOR_INDEX_CACHE.delete(oldest);
	}
	ANCHOR_INDEX_CACHE.set(filePath, {
		mtimeMs: stats.mtimeMs,
		size: stats.size,
		index,
	});
	return { index };
}

/**
 * Resolve one anchor token against the file's CURRENT content.
 *
 * Unique match only, exactly like `resAnchorFromMap` in
 * `src/hashline/resolve.ts`: an anchor that matches no line or more than one
 * line has no answer here either.
 */
export function resolveHashlineAnchor(
	filePath: string,
	anchor: unknown,
): HashlineAnchorResolution {
	const token = normalizeHashlineAnchorToken(anchor);
	if (token === undefined) return { failure: "not_an_anchor" };
	const built = buildAnchorIndex(filePath);
	if ("failure" in built) return { failure: built.failure };
	const line = built.index.get(token);
	if (line === undefined) return { failure: "anchor_not_found" };
	if (line === null) return { failure: "anchor_ambiguous" };
	return { line };
}
