import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Ground truth for `pi-hashline-edit-pro`'s line anchors (#2423 review round 1,
 * finding F1).
 *
 * `tests/fixtures/hashline-edit-pro/anchor-vectors.json` was generated by
 * running the EXTENSION's own `_lineHashesPure` with the real `xxhash-wasm` —
 * see the sibling `generate-anchor-vectors.mjs` and the `upstream` block in the
 * JSON for the commit.
 *
 * Tests take their anchors from here rather than from
 * `clients/hashline-anchor.ts`. Two reasons, both deliberate:
 *
 * 1. A test that asks the module under test what the right answer is proves
 *    nothing. These anchors come from the other project's arithmetic.
 * 2. Importing the production module would make every case in a file red with
 *    a module-resolution error when the module is absent, which is a much
 *    weaker red-first proof than an assertion failure.
 */
export interface HashlineAnchorVectors {
	upstream: {
		repo: string;
		branch: string;
		commit: string;
		generatedWith: string;
		source: string[];
	};
	xxh32: Array<{ input: string; h32: number }>;
	lineAnchors: Record<string, { content: string; hashes: string[] }>;
}

let cached: HashlineAnchorVectors | undefined;

export function loadHashlineAnchorVectors(): HashlineAnchorVectors {
	if (cached) return cached;
	cached = JSON.parse(
		fs.readFileSync(
			path.resolve(
				import.meta.dirname,
				"..",
				"fixtures",
				"hashline-edit-pro",
				"anchor-vectors.json",
			),
			"utf8",
		),
	) as HashlineAnchorVectors;
	return cached;
}

/** One named fixture file: its content and the anchor of each of its lines. */
export function hashlineFixture(name: string): {
	content: string;
	/** `anchorFor(1)` is the anchor of line 1. */
	anchorFor: (line: number) => string;
	lineCount: number;
} {
	const entry = loadHashlineAnchorVectors().lineAnchors[name];
	if (!entry) throw new Error(`unknown hashline fixture "${name}"`);
	return {
		content: entry.content,
		anchorFor: (line: number) => {
			const anchor = entry.hashes[line - 1];
			if (anchor === undefined)
				throw new Error(`fixture "${name}" has no line ${line}`);
			return anchor;
		},
		lineCount: entry.hashes.length,
	};
}
